version: '3.8'
services:
  db:
    image: mariadb:10.4
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    volumes:
      - ../app.sql:/docker-entrypoint-initdb.d/app.sql

  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:1-3.8-buster
    volumes:
      - ../..:/workspaces:cached
    command: /bin/bash -c "apt-get update && apt-get install -y fonts-thai-tlwg telnet  && sleep infinity"
    network_mode: service:db # Make sure the app runs on the same as the database container


